version: "3.8"

services:
  node-1:
    image: hyperledger/besu:25.3.0
    container_name: besu-node-1
    volumes:
      - ./network/node-1/data:/opt/besu/data
      - ./network/node-1/genesis.json:/opt/besu/genesis.json
    networks:
      - shared_network
    command: >
      --data-path=/opt/besu/data
      --genesis-file=/opt/besu/genesis.json
      --host-allowlist="*"
      --p2p-port=30303

  node-2:
    image: hyperledger/besu:25.3.0
    container_name: besu-node-2
    depends_on:
      - node-1
    volumes:
      - ./network/node-2/data:/opt/besu/data
      - ./network/node-2/genesis.json:/opt/besu/genesis.json
    networks:
      - shared_network
    ports:
      # RPC access
      - "8546:8546"
    env_file:
      - .env
    command: >
      --data-path=/opt/besu/data
      --genesis-file=/opt/besu/genesis.json
      --rpc-http-enabled
      --rpc-http-api=ETH,NET,QBFT,WEB3
      --host-allowlist="*"
      --rpc-http-cors-origins="all"
      --Xdns-enabled=true
      --Xdns-update-enabled=true
      --bootnodes=${BOOTNODE_ENODE}
      --p2p-port=30304
      --rpc-http-port=8546
      --rpc-http-host=0.0.0.0

  node-3:
    image: hyperledger/besu:25.3.0
    container_name: besu-node-3
    depends_on:
      - node-1
      - node-2
    volumes:
      - ./network/node-3/data:/opt/besu/data
      - ./network/node-3/genesis.json:/opt/besu/genesis.json
    networks:
      - shared_network
    env_file:
      - .env
    command: >
      --data-path=/opt/besu/data
      --genesis-file=/opt/besu/genesis.json
      --host-allowlist="*"
      --Xdns-enabled=true
      --Xdns-update-enabled=true
      --bootnodes=${BOOTNODE_ENODE}
      --p2p-port=30305

  node-4:
    image: hyperledger/besu:25.3.0
    container_name: besu-node-4
    depends_on:
      - node-1
      - node-3
    volumes:
      - ./network/node-4/data:/opt/besu/data
      - ./network/node-4/genesis.json:/opt/besu/genesis.json
    networks:
      - shared_network
    env_file:
      - .env
    command: >
      --data-path=/opt/besu/data
      --genesis-file=/opt/besu/genesis.json
      --host-allowlist="*"
      --Xdns-enabled=true
      --Xdns-update-enabled=true
      --bootnodes=${BOOTNODE_ENODE}
      --p2p-port=30306

  node-5:
    image: hyperledger/besu:25.3.0
    container_name: besu-node-5
    depends_on:
      - node-1
      - node-4
    volumes:
      - ./network/node-5/data:/opt/besu/data
      - ./network/node-5/genesis.json:/opt/besu/genesis.json
    networks:
      - shared_network
    env_file:
      - .env
    command: >
      --data-path=/opt/besu/data
      --genesis-file=/opt/besu/genesis.json
      --host-allowlist="*"
      --Xdns-enabled=true
      --Xdns-update-enabled=true
      --bootnodes=${BOOTNODE_ENODE}
      --p2p-port=30307

  node-6:
    image: hyperledger/besu:25.3.0
    container_name: besu-node-6
    depends_on:
      - node-1
      - node-5
    volumes:
      - ./network/node-6/data:/opt/besu/data
      - ./network/node-6/genesis.json:/opt/besu/genesis.json
    networks:
      - shared_network
    env_file:
      - .env
    command: >
      --data-path=/opt/besu/data
      --genesis-file=/opt/besu/genesis.json
      --host-allowlist="*"
      --Xdns-enabled=true
      --Xdns-update-enabled=true
      --bootnodes=${BOOTNODE_ENODE}
      --p2p-port=30308

  node-7:
    image: hyperledger/besu:25.3.0
    container_name: besu-node-7
    depends_on:
      - node-1
      - node-6
    volumes:
      - ./network/node-7/data:/opt/besu/data
      - ./network/node-7/genesis.json:/opt/besu/genesis.json
    networks:
      - shared_network
    env_file:
      - .env
    command: >
      --data-path=/opt/besu/data
      --genesis-file=/opt/besu/genesis.json
      --host-allowlist="*"
      --Xdns-enabled=true
      --Xdns-update-enabled=true
      --bootnodes=${BOOTNODE_ENODE}
      --p2p-port=30309

# docker network create shared_network
networks:
  shared_network:
    name: shared_network
    driver: bridge
    external: true
