#!/bin/bash

set -e

# Default to Docker mode unless specified otherwise
MODE=${1:-docker}

# Path to the bootnode key file
BOOTNODE_KEY_PATH="network/node-1/data/key.pub"

if [ ! -f "$BOOTNODE_KEY_PATH" ]; then
  echo "Error: Bootnode key file not found at ${BOOTNODE_KEY_PATH}"
  exit 1
fi

# Extract the bootnode key (removing 0x prefix if present)
BOOTNODE_KEY=$(cat "$BOOTNODE_KEY_PATH" | sed 's/^0x//')

# Set the bootnode host based on the mode
if [ "$MODE" = "docker" ]; then
  BOOTNODE_HOST="node-1"
else
  BOOTNODE_HOST="127.0.0.1"
fi

# Get the bootnode P2P port
BOOTNODE_P2P_PORT=$(cat "network/node-1/p2p-port")

# Extract network ID from genesis.json
NETWORK_ID=$(grep -o '"chainId" : [0-9]*' network/node-1/genesis.json | awk '{print $3}')

CURRENCY_NAME="Ether"
CURRENCY_SYMBOL="ETH"
CURRENCY_DECIMALS=18

# Create or overwrite the .env file
cat > .env << EOF
# Generated by generate-env.sh in ${MODE} mode on $(date)
BOOTNODE_KEY=${BOOTNODE_KEY}
BOOTNODE_HOST=${BOOTNODE_HOST}
BOOTNODE_P2P_PORT=${BOOTNODE_P2P_PORT}
BOOTNODE_ENODE=enode://${BOOTNODE_KEY}@${BOOTNODE_HOST}:${BOOTNODE_P2P_PORT}
NETWORK_ID=${NETWORK_ID}
CURRENCY_NAME=${CURRENCY_NAME}
CURRENCY_SYMBOL=${CURRENCY_SYMBOL}
CURRENCY_DECIMALS=${CURRENCY_DECIMALS}
EOF

echo "Generated .env file for ${MODE} mode"
echo "Bootnode enode URL: enode://${BOOTNODE_KEY}@${BOOTNODE_HOST}:${BOOTNODE_P2P_PORT}"
